# Generated by Django 4.1.7 on 2023-05-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_social_github_profile_social_twitter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['created']},
        ),
    ]
