# Generated by Django 4.1.7 on 2023-05-07 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_review_owner_alter_review_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-Vote_ratio', '-Vote_total', 'title']},
        ),
    ]
