# Generated by Django 4.1.7 on 2023-03-05 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tag_project_demo_link_project_source_link_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_time',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='created_time',
            new_name='created',
        ),
    ]
