# Generated by Django 4.1.7 on 2023-03-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_created_time_project_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='Vote_ratio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='Vote_total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
